[package]
name        = "flixapi"
description = "An Effect-Oriented API framework for Flix"
version     = "0.1.0"
flix        = "0.65.0"
authors     = ["Valentin Erokhin <hello@valentin.wiki>"]
repository = "github:saviorand/flixapi"

[dependencies]
"github:mlutze/flix-json" = "0.13.1"